export { default as Navigation } from "./navigation";
export { default as Footer } from "./footer";
export { default as Home } from "../home/home";
export { default as Introduction } from "../introduction/introduction";
export { default as Introduction2 } from "../introduction/introduction2";
export { default as Introduction3 } from "../introduction/introduction3";
export { default as Builder } from "../builder/builder";
export { default as Assay } from "../assay/assay";
export { default as Analysis } from "../analysis/analysis";
export { default as Results } from "../results/results";
export { default as LoginPage } from "./login"